name: Publish on Master
on:
  push:
    branches:
      - master
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-executable: bin/gradle